---
validators: 2
mnemonic: code code code code code code code code code code code quality

rootchain:
  accounts: 50
  chain_id: 1
  data_path: /etc/rootchain
  image: trufflesuite/ganache:v7.9.2
  hardfork: shanghai
  miner_coinbase_address: "0x85dA99c8a7C2C95964c8EfD687E95E632Fc533D6"
  rpc_port: 8545
