---
name: ci

on:
  pull_request:
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.12"      # https://www.python.org/doc/versions/
  HADOLINT_VERSION: "2.12.0"  # https://github.com/hadolint/hadolint/releases

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable
      - name: Kurtosis Lint
        run: kurtosis lint ${{ github.workspace }}

      - name: Install YAML linter
        run: pip install yamllint
      - name: Run YAML linter
        run: yamllint --config-file .yamllint.yml .

      - name: Install Dockerfile linter
        run: |
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v${{ env.HADOLINT_VERSION }}/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint
      - name: Run Dockerfile linter
        run: find . -type f -name 'Dockerfile*' | sort | xargs -I {} hadolint --config .hadolint.yml {}

  starlark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable

      - name: Run Starlark
        run: kurtosis run ${{ github.workspace }}
