---
name: deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - config_with_custom_rootchain.yml
          - config_with_rootchain_rpc_url.yml
    steps:
      - uses: actions/checkout@v4
      - name: Deploy devnet
        uses: kurtosis-tech/kurtosis-github-action@v1
        with:
          path: .
          args: config/${{ matrix.directory }}
